<?php

return [

    /*
     * The token generated by Slack with which to verify if a incoming slash command request is valid (deprecated).
     */
    'token' => env('SLACK_VERIFICATION_TOKEN'),

    /*
    |-------------------------------------------------------------
    | Your validation token from "App Credentials"
    |-------------------------------------------------------------
    */
    'signing_secret' => env('SLACK_SIGNING_SECRET', 'your-signing-secret'),

    /*
    |-------------------------------------------------------------
    | Events Request URL — path, where events will be served
    |-------------------------------------------------------------
    */
    'route' => '_slack-events',

];
